kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: mariadb-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: mariadb-sc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
